### ISSUE TITLE
sys_category doesn't get saved in the repository

### ISSUE THREAD

**Issue by williwacker** [SicorDev/sic_address#1]
Thanks for this extension having the configurable fields.  
I have added address entries into the repository but the sys_category number doesn't get stored correctly, and the category tree is not resolved in edit mode.

**Comment by SicorDev** [comment]
Hi, thanks for trying the extension!

In order to further analyze the problem, are you using the extension standalone or on top of tt_address? And with number you mean counting the checked categories, yes?

**Comment by williwacker** [comment]
Hi,
I am using it standalone. And with number I mean the sys_category uid.

**Comment by SicorDev** [comment]
That's not how sys_category is utilized. There's a m:n relation in the database via the table sys_category_record_mm, which allows you to assign multiple categories to another db record. I think the categories field in the adress table just counts how many categories are assigned, from 0-n.

You don't have to access the categories by uid, as the Address repository will already return an array of Category objects which then have a 'title' attribute for example.

Coming to the second half of your report: What are you editing? An address record in the Backend? The category tree should be the first element after language and the hidden flag. You're not seeing it?

**Comment by williwacker** [comment]
Meanwhile I have tried the tt_address mapping option which is working much better. With the option of specifying the fields manually I was running from one exception to the other. What I am missing is a sort option. Currently the records are shown in the order they are in the database.
Whould it be possible adding this feature?  Tx

**Comment by SicorDev** [comment]
Good to hear that this works better for you, albeit for us it'd certainly be better to get those errors you mentioned fixed. We'd definitely be willing to help you iron things out if you'd give it another try ;-)

Sorting can be configured in a plugin dropdown:
![grafik](https://user-images.githubusercontent.com/24271592/36475525-37d18ce6-16fb-11e8-9d97-951fc30e6869.png)

**Comment by williwacker** [comment]
How can I manage creating a link to a single address view page out of a list template?  Tx

**Comment by SicorDev** [comment]
This is a future enhancement currently still on our todo list. In all our Live usecases so far we usually display all detail in the list already and just shrink it with filters like here for example:

https://www.oberguenzburg.de/wirtschaft/gewerbeverzeichnis.html

The detail plugin is currently used only to display a dedicated address e.g. on an imprint page.

**Comment by SicorDev** [comment]
We just released sic_address version 1.0.5 to TER containing a fix for the initialy reported problem with the category tree. 

We had a problem with language mapping, so when the address had sys_language_uid = -1 and the categories sys_language_uid = 0 it didn't find them.

Please feel free to open another issue if there's other problems remaining.
