### ISSUE TITLE
Error when trying to install Ver. 2.0.1

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#16]
I get the error:

`Uncaught TYPO3 Exception: #1278450972: Class SICOR\SicAddress\Domain\Model\Address does not exist. Reflection failed. | TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException thrown in file /kunden/acde/fsdsf/xxx/xxx/typo3cms/typo3_src-9.5.4/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php in line 363. `

I cleared all caches and used database analyzer. When I try to add this field to the table

`ALTER TABLE `tx_sicaddress_domain_model_address` ADD `uid` INT AUTO_INCREMENT NOT NULL`

I get the error message:
```
Database update failed
`Error: Incorrect table definition; there can be only one auto column and it must be defined as a key`
```

Regards
Hobokens

**Comment by SicorDev** [comment]
Did you run the generate process?

Class SICOR\SicAddress\Domain\Model\Address is available after generation only.
The fields of table tx_sicaddress_domain_model_address are also generated, you do not need to alter the table.

**Comment by Hobokens** [comment]
Oh, that's what I missed. Now everything is fine. Thanks for your fast reaction.
