### ISSUE TITLE
Problems to install Ver. 2.0.1

### ISSUE THREAD

**Issue by morange** [SicorDev/sic_address#19]
Hej Folks,
i tried to install version 2.0.1 at my TYPO3 (9.5.5). The system runs on XAMPP 7.2.11. Apparently the problem is that the table *tx_sicaddress_domain_model_address* can not be installed.

If i tried to install the table about SequelPro and became this answer: *Incorrect table definition; there can be only one auto column and it must be defined as a key*.

I cleared the caches and install the Ext in the template. :/

Do you have an idea, what's happend?
best regards, Steffen

**Comment by SicorDev** [comment]
Hi Steffen,

did you upgraded from an older version or installed a fresh one?
When do you get errors? During installation or during generation?

**Comment by coffermann** [comment]
Hi Team,

Typo3 9.5.5. - Weiland - Musterprojekt for testing

I have just tried to start it from scratch.
After configuration to delveloper mode  you get the failure notice in frontend.:

Oops, an error occurred!
Table 'db130400_950.tx_sicaddress_domain_model_address' doesn't exist

More information regarding this error might be available online.

Then I tried a databasecompare -and got the same message as described by Steffen.

VG Christian

**Comment by coffermann** [comment]
Here ist the screenshot

VG Christian

![SIC-Fehlermeldung](https://user-images.githubusercontent.com/30771286/56199816-ea331a80-603d-11e9-9991-9b5d678f6de4.jpg)

**Comment by SicorDev** [comment]
Hi Steffen,

the bug was located and fixed in 2.0.2.

Version 2.0.2 will be released soon.

**Comment by morange** [comment]
(Y) thx
