### ISSUE TITLE
Erro when creating a sicaddress

### ISSUE THREAD

**Issue by ehontheim** [SicorDev/sic_address#2]
a) List modul
b) Page with type folder
c) static template is included one level abvoe the folder
d) tt_address Mapping is not in use
e) when trying to create a sicaddress the following error appears

_#1438185331: At least one "types" array must be defined for table tx_sicaddress_domain_model_address, preferred "0" (More information)

UnexpectedValueException thrown in file
/............../typo3cms/typo3_src-8.7.5/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseRecordTypeValue.php in line 43._

**Comment by SicorDev** [comment]
Can you please check if the file typo3conf\ext\sic_address\Configuration\TCA\tx_sicaddress_domain_model_address.php exists? 

If it's there, please attach it.

If it's not there, please open the backend module and Click the button "Generate Model, TCA, l18n, DB". Does the file exist now?

**Comment by ehontheim** [comment]
Hi, 

 

thanks fort he quick response

 

a.	tx_sicaddress_domain_model_address.php doesn’t exist. Just tx_sicaddress_domain_model_domainproperty.php is in the mentioned folder
b.	I’m lost. Which button please? Where and how to be found in the backend module?

 

BR

 

Erwin Hontheim

 

Von: SICOR KDL DevTeam [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. Februar 2018 15:00
An: SicorDev/sic_address <sic_address@noreply.github.com>
Cc: ehontheim <erwin@hontheim.info>; Author <author@noreply.github.com>
Betreff: Re: [SicorDev/sic_address] Erro when creating a sicaddress (#2)

 

Can you please check if the file typo3conf\ext\sic_address\Configuration\TCA\tx_sicaddress_domain_model_address.php exists?

If it's there, please attach it.

If it's not there, please open the backend module and Click the button "Generate Model, TCA, l18n, DB". Does the file exist now?

**Comment by SicorDev** [comment]
I see. In the extension configuation please enable the Backend Module:
![grafik](https://user-images.githubusercontent.com/24271592/36485559-d0543312-171c-11e8-86c9-68991e224604.png)

In the module then hit the blue button:
![grafik](https://user-images.githubusercontent.com/24271592/36485743-197e4d7a-171d-11e8-91f8-5a4573900f70.png)

This should write the missing file. Does it? Actually it should be written automatically when the extension is turned on, so the behaviour you experience is kinda odd.

**Comment by SicorDev** [comment]
Added a Troubleshooting section in the documentation, explaining the self-modifying nature of the extension: https://www.sicor-kdl.net/dokumentation-sic_address/

Can't do more without more info :-)

**Comment by SicorDev** [comment]
While working on something different, I think I saw and fixed the problem you encountered. If you're still interested, please give version 1.0.6 a try.
