### ISSUE TITLE
Respect available language records in AtoZ menue

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#26]
Hi,
I'm sorry, it's me again.

After updating to version 2.1.1. I still have the problem that was solved before with the pull request #23. I

**Comment by SicorDev** [comment]
Hi,

your pull code is still there:
https://github.com/SicorDev/sic_address/blob/master/Classes/Domain/Repository/AddressRepository.php

Maybe something went wrong during the update process. Could you please remove you local sic_address extension and install it again from TER?

**Comment by Hobokens** [comment]
After removing the extension and installing it again the described problem remains. Letters in the menu have links even if there are no corresponding data records in the selected language. In other words, links are displayed for all letters as soon as there is a record in the default language.
In fact, only records in the selected language will be displayed. The remaining links do not lead to a display.

**Comment by SicorDev** [comment]
fixed in 2.1.2 which has been uploaded a few minutes ago.
