### ISSUE TITLE
It should work under PHP 7.3

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#29]
When I install sic_address 2.2.1 under PHP 7.3.11 and TYPO3 9.5.8 then the Extension Manager ends in an error message.

[error.txt](https://github.com/SicorDev/sic_address/files/3906291/error.txt)

see also https://github.com/in2code-de/lux/issues/5

**Comment by SicorDev** [comment]
We had some issues with PHP 7.3, too
 https://github.com/SicorDev/sic_address/issues/25

We also tried some fixes, but at the end decided to wait until the issues get fixed in TYPO3 Fluid itself. For us it didn't made sense to fix Fluid issues in our extension.

**Comment by SicorDev** [comment]
Support for PHP 7.3 and 7.4 has been activated in 2.4.1.

For more details read the CHANGELOG, please.
