### ISSUE TITLE
don´t work..

### ISSUE THREAD

**Issue by quadronet** [SicorDev/sic_address#3]
after Install an create new entry i see this:

Datenbank-Fehler
Unknown column 'tx_sicaddress_domain_model_address.company' in 'field list'. Es ist ein SQL-Fehler aufgetreten. Dies kann auf eine Schema-Abweichung zwischen TCA und der Datenbank hindeuten. Versuchen Sie im Install Tool einen Datenbank-Vergleich durchzuführen.

**Comment by SicorDev** [comment]
I just uploaded version 1.0.8 to the repository, which no longer requires a "company" field when using the extension without tt_address underneath. Please give it another try.

**Comment by franzholz** [comment]
This error still exists in the most current sic_address 2.3.1 . tt_address should be used in this case.

_Oops, an error occurred! Code: 20200121151330e6e88803 Unknown column 'tx_sicaddress_domain_model_address.company' in 'where clause' exception code:1472074379 file:/typo3/sysext/extbase/Classes/Persistence/Generic/Storage/Typo3DbBackend.php line:492 fh_debug trace: file: /typo3/sysext/extbase/Classes/Persistence/Generic/Backend.php" line:213 function:getObjectCountByQuery file: /typo3/sysext/extbase/Classes/Persistence/Generic/PersistenceManager.php" line:114 function:getObjectCountByQuery file: /typo3/sysext/extbase/Classes/Persistence/Generic/QueryResult.php" line:134 function:getObjectCountByQuery file: " line: function:count file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:467 function:count file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:431 function:convertNodeToBoolean file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:316 function:evaluateTerm file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:302 function:parseTermToken file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:274 function:parseStringToken file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:255 function:parseBracketToken file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:228 function:parseNotToken file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:206 function:parseCompareToken file: /typo3fluid/fluid/src/Core/Parser/BooleanParser.php" line:184 function:parseAndToken _

**Comment by SicorDev** [comment]
Did you imported the tt_address fields?

**Comment by franzholz** [comment]
I have made sic_address working on a test environment. Now I am porting it to a live environment. However because of these errors it does not work any more. So I have compared these 2 installations. Then I have discovered that the tx_sicaddress_domain_model_domainproperty columns have been missing. So I have exported and finally imported them via SQL. 

Is this wrong? Should I have entered the column names somehow manually?


[columns.tar.gz](https://github.com/SicorDev/sic_address/files/4091554/columns.tar.gz)

**Comment by franzholz** [comment]
Now I have gone back to sic_address 2.2.1 ,
Everything works now also on the new live website without any error message.

**Comment by SicorDev** [comment]
We're not sure what you're doing...
The table tx_sicaddress_domain_model_address shouldn't even exist when using the extension in tt_address mode.

**Comment by franzholz** [comment]
I have activated the tt_address mode in the Extension Manager for sic_address. 
The Install Tool seems to have created all tables of sic_address.

```
basic.searchFields
company,name,title,city

tt_address Mapping
basic.ttAddressMapping 
x checked

templates.templateSet
nicosdir

Developer Mode
modules.developerMode
x checked


```

Only after i had imported the SQL field names I was able to see all plugin settings with all options.
E.g. "A-Z Field " did not show any field name.




```

**Comment by franzholz** [comment]
Now I have found the solution.
The "Address Management" backend must be executed once.
Then execute "Generate Model, TCA, i18n DB for the internal select box selection.

And also the extension sic_address inside of typo3conf/ext must be writable.

Maybe this is missing in the docs, or I could not find it.

**Comment by SicorDev** [comment]
It's located in the "Troubleshooting" section of the documentation under "Updating the extension".

**Comment by franzholz** [comment]
oh yeah. Now I have noticed that "Troubleshooting" is a clickable topic which opens the contents only if you click on it. I did not notice this before.
