### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#30]
I have found misspellings and missing hints.

> sic_address can seemlessly work on top of an exsiting installation already running a tt_address database
==> database table

> develpoment version of the website
==> development

> Once the prerequisites are done, please open the backend and 
==> open the backend module "Address Management" / "Database Editor"

> and execute these steps in order
==> in this order

> Click the button "Import tt_address Field Definition".
==> Select "external". You see: tt_addresss. ...

> Click the button "Generate Model, TCA, l18n, DB".
==> Select "internal" ...
==> You see: Extension successfully updated.

> Since version 1.1.x a detail page can be directly linked in list module within the plugin settings if desired.
==> in the list module

**Comment by SicorDev** [comment]
Done, thx.
