### ISSUE TITLE
Limit the system categories to one page id.

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#33]
Is there already a way to limit the categories which are shown in the drop down box to only one page? The problem is that there are several sic_address plugins. Each of them shall only have the categories which are stored on that page. At the moment all categories of all pages appear on all select boxes. 

AddressController.php has this viewAssign command:
`$this->view->assignMultiple(array(
            'currentCategory' => $currentCategory,
            'currentCategories' => $currentCategories,
            'args' => $args,
            'categories' => $categories,
            'settings' => $this->settings,
            'mapSettings' => $this->settings['map'],
            'addresses' => $addresses,
            'countries' => $countries,
            'centerAddress' => $centerAddress,
            'distances' => $this->getDistances(),
            'radius' => $args['distance'],
            'contentUid' => $this->configurationManager->getContentObject()->data['uid']
        ));`

However I see no way to limit those categories to only one page.

At the moment there is a setting of rootCategory in the plugin flexform. Maybe a categoryPage could be added here?

**Comment by SicorDev** [comment]
Have you tried organizing your categories in a tree with subfolders? You should be able to limit each plugin to another subfolder.

**Comment by franzholz** [comment]
I have now added a newly created parent category to a group of categories. I have added a root category named "Main category for filter". However the drop down box still shows all categories. Am I missing something how I can change the category drop down box to only show the child categories of a selected root category?

**Comment by SicorDev** [comment]
Please try selecting your parent category in the "categories" tab:

![grafik](https://user-images.githubusercontent.com/24271592/70782569-98d35a80-1d87-11ea-8263-c3a63b872f53.png)

**Comment by franzholz** [comment]
Yes, that is a working solution. Thank you!
