### ISSUE TITLE
search result error

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#37]
In the latest version sic_address 2.3.2 I get an error message instead of a search result.

[Fehler-Suchergebnis.txt](https://github.com/SicorDev/sic_address/files/4112151/Fehler-Suchergebnis.txt)

This works fine in version 2.2.1.

**Comment by SicorDev** [comment]
A new, clearly visible note has been added to our documentation under Troubleshooting, to prevent this issue in future.
