### ISSUE TITLE
search result empty record list

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#38]
I am using sic_address 2.2.1, however I have seen it also with 2.3.1. The result list of a search list a lot of records. However each record is empty. The field values the of tt_address records have not been inserted into the fluid template. Even the page browser is used, when many empty records have been shown. However those records are not really empty in the database. I have almost 3 identical websites. However this happens only on one of them. All the setup, the template, the plugins and the extension sic_adress are identical. And I have done also the steps in the Sic Address backend module.

[leeres-Suchergebnis.txt](https://github.com/SicorDev/sic_address/files/4112752/leeres-Suchergebnis.txt)

**Comment by franzholz** [comment]
Now I have found this issue. It is obviously the same.
**Please put it into the documentation!**

https://github.com/SicorDev/sic_address/issues/7

**Comment by SicorDev** [comment]
A new, clearly visible note has been added to our documentation under Troubleshooting, to prevent this issue in future.
