### ISSUE TITLE
provide composer package

### ISSUE THREAD

**Issue by colorcube** [SicorDev/sic_address#39]
Add composer.json and publish on packagist.
Here's a composer.json that should work:
(I'm a bit unsure if the uppercase in SICOR\\SicAddress\\ work)

    {
    "name": "sicor/sic-address",
    "type": "typo3-cms-extension",
    "description": "Address Extension that can either enhance or replace tt_address.",
    "keywords": [
        "TYPO3",
        "extension",
        "addresses"
    ],
    "homepage": "https://github.com/SicorDev/sic_address",
    "authors": [
        {
        "name": "SICOR DEVTEAM",
        "role": "Developer"
        }
    ],
    "license": "GPL-2.0-or-later",
    "require": {
        "typo3/cms-core": "^7.6 || ^8.7 || ^9.5",
        "php": ">=7.2"
    },
        "autoload": {
            "psr-4": {
                "SICOR\\SicAddress\\": "Classes"
            }
        },
    "extra": {
        "typo3/cms": {
        "extension-key": "sic_address"
        }
    },
    "replace": {
        "typo3-ter/sic-address": "self.version"
    }
    }

**Comment by SicorDev** [comment]
please check https://github.com/SicorDev/sic_address/issues/40 for futher infos in this matter.
