### ISSUE TITLE
Routing for TYPO3 9.5.x

### ISSUE THREAD

**Issue by morange** [SicorDev/sic_address#41]
Hello Sicor Team,
many thx for your great extension. 

I try to put the routing together for the extension, but unfortunately I only get error messages.
I try to create realname URL with the following Yaml configuration:

  Sic_address:
    type: Extbase
    extension: Sicaddress
    plugin: Address
      routes:
        - routePath: '/ page- {page}'
          _controller: 'Address :: list'
          _arguments:
            page: '@ widget_0 / currentPage'

        - routePath: '/ {address_slug}'
          _controller: 'Address :: show'
          _arguments:
            'address_slug': 'address'

        - routePath: '/ page- {search}' '
          _controller: 'Address :: search'
          _arguments:
            'search': 'search'

      defaultController: 'Address :: list'

    defaults:
      page: '0'

    requirements:
      page: '\ d +'

    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'

        page label:
          type: LocaleModifier
          default: 'page'
          localeMap:
            - locale: 'de _. *'
              value: 'page'
            - locale: 'en _. *'
              value: 'side'

      address_slug:
        type: PersistedPatternMapper
        tableName: 'tt_address'
        routeFieldPattern: '^ (? P <slug>. +) - (? P <uid> \ d +) $'
        routeFieldResult: '{slug} - {uid}'

      search:
        type: StaticRangeMapper
        start: '1'
        end: '100'

Can you help me or provide some tips for a correct configuration? Documentation would also be very useful.

Many thanks and best regards
Steffen

**Comment by SicorDev** [comment]
Please have a look at #28 if this helps you and give us feedback there in case.
