### ISSUE TITLE
combine dropdown and a-z field

### ISSUE THREAD

**Issue by morange** [SicorDev/sic_address#42]
Hello SicorDev-Team,
it is possible to combine the dropdown and the a-z fields?

I use the extension to list about 500 people. These people are sorted alphabetically and can be selected using the a-z fields and the dropdown field.

I use TYPO3 9.5.17 and SIC_ADDRESS 2.4.2

Best greetings
m.orange

**Comment by SicorDev** [comment]
At present one of those filters will reset the other, no change in this behaviour is intended right now.
