### ISSUE TITLE
 misspelling on website

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#44]
The website has some misspellings.

https://www.sicor-kdl.net/index.php?id=111

There's explanations for the available options. ==> Here are explanations ...
when the fields have common english names  ==> English ....
exsiting installation ==> existing
already running a tt_address database table  ==> the tt_address ....
it's still recommended  ==> it is ...
sic_address works with sys_category exclusively. ==> works exclusively with sys_category
Third party extensions requiring tt_address_group will no longer work properly. You have to deactivate them or port them over to use sys_category.
You see: tt_addresss. ==> ... tt_address

**Comment by SicorDev** [comment]
Thank you very much!
