### ISSUE TITLE
Respect language for a-z menu

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#45]
I have a lot of German address records in tt_address, of which only some are translated into English. However, the English A-Z menu also highlights letters for which there are only German records available. If I click on these letters then, of course no records are displayed. (TYPO3 10.4.10, sic_address 3.1.2, tt_address 5.2.)

I know, that this issue was [discussed before](https://github.com/SicorDev/sic_address/issues/26).

**Comment by SicorDev** [comment]
Hello, I'd have some time this week to look into this. Do you have a development Site where I could work on the problem?

**Comment by Hobokens** [comment]
You can see the problem on this site:
https://www.hfm-wuerzburg.de/lehre
My development Site is not on github but local.

**Comment by SicorDev** [comment]
Fixed with 3.1.4, thanks for your patience!
