### ISSUE TITLE
\PropertyNotAccessibleException: The property \"\" on the subject does not exist

### ISSUE THREAD

**Issue by junfan59** [SicorDev/sic_address#46]
Dear,

I try to use this extension without any success...

**First problem :** 

I added the static template.

I added some fields with the module (name, phone, ...)

I added a record into a sys_folder page (stock_directory)

Into a page I added the plugin as content in "list" mode with my "stock_directory" configured as record storage page.
If I don't setup the "filter field" I get an message `"No items found or no filters given!"`

So I select "uid" as filter field (the only item).

When I preview this page in frontend I get an oops error : 
`Oops, an error occurred! Code: 20210211174016508d4740 - {"exception":"TYPO3\\CMS\\Extbase\\Reflection\\Exception\\PropertyNotAccessibleException: The property \"\" on the subject does not exist`.

**Second problem :** 
There is some label issues not displayed in backend as picture below
![Capture d’écran 2021-02-11 à 18 58 53](https://user-images.githubusercontent.com/7127614/107678308-83afcf80-6c9b-11eb-8961-e909a19222f8.png)

Is it some bugs or missing configuration ?

If you can help, thanks you so much !

**Comment by junfan59** [comment]
I have debuging the template "NicosList.html for testing purpose and I can see that "addresses" is NULL
![Capture d’écran 2021-02-12 à 11 55 23](https://user-images.githubusercontent.com/7127614/107759930-48f47880-6d29-11eb-8a76-709b6625ecbc.png)
Why please ? The doc is very very very light...

**Comment by junfan59** [comment]
When I add a new field like "name" or "email", the plugin add 2 lines into database : 
![Capture d’écran 2021-02-12 à 14 29 50](https://user-images.githubusercontent.com/7127614/107774068-d42c3900-6d3e-11eb-970c-a54537a6a039.png)

So I think because of that, the AZ-Field display empty line in the dropdown select list
![Capture d’écran 2021-02-12 à 14 30 52](https://user-images.githubusercontent.com/7127614/107774222-0178e700-6d3f-11eb-9e4e-82dd139d12cc.png)

So maybe because of this empty line, in template `{addresses}` is empty...?

Is someone can use this plugin ?!?

**Comment by morange** [comment]
Hello Junfan59,
yes i use this extension. I think you have to import your data from tt_address. ;) 
Go to Settings > Extension Configuration > sic_address > modules and activate there Developer Mode. Maybee you have to deactivate in Settings > Extension Configuration > tt_address > Basic this filed basic.readOnlyNameField.

Then go to Address Management to import your Data. 

I looked for an while, but it works then.


Best greetings
Steffen

**Comment by SicorDev** [comment]
Hello, I'd have some time this week to look into this.  Is the problem still happening? Do you have a development Site where I could work on the problem?

**Comment by morange** [comment]
Hi SicorDev Team,

thx for your answer. The development site is actually not online, if it’s help you i can push it in the next days, so you can use it. Or you can take my dude install…


Thx, Steffen


Steffen Matthes

M.:  0163 7937697
E:    ***@***.*** ***@***.***>

**Comment by SicorDev** [comment]
The latest version of the extension, 3.1.4 fixes two issues addressed here:

* The TCA generator has been improved for TYPO 3 10, so missing labels are now shown properly.
* There are no longer duplicate DB entries created

I'd assume the later fixes the other mentioned effects as well. If not, please open a new issue with updated problem description.
