### ISSUE TITLE
wrong file suffix

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#49]
In File `ext_tables.php` is the line `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:sic_address/Configuration/TSconfig/Page/wizard.txt">');`
The correct file is `wizard.typoscript`

**Comment by SicorDev** [comment]
Fixed with 3.1.4, thanks for your patience!
