### ISSUE TITLE
Allow several paths for templates, layouts and partials

### ISSUE THREAD

**Issue by nebrot** [SicorDev/sic_address#5]
Most extensions allow to define serveral different paths for templates, layouts and partials like:
```
plugin.tx_news {
	view {
		templateRootPaths {
			0 = EXT:news/Resources/Private/Templates/
			1 = {$plugin.tx_news.view.templateRootPath}
			100 = EXT:myext/Resources/Private/Extensions/news/Templates
		}

		partialRootPaths {
			0 = EXT:news/Resources/Private/Partials/
			1 = {$plugin.tx_news.view.partialRootPath}
			100 = EXT:myext/Resources/Private/Extensions/news/Partials
		}

		layoutRootPaths {
			0 = EXT:news/Resources/Private/Layouts/
			1 = {$plugin.tx_news.view.layoutRootPath}
			100 = EXT:myext/Resources/Private/Extensions/news/Layouts
		}
	}
}
```

Currently only this is possible with sic_address to use own files:
```
plugin.tx_sicaddress_sicaddress {
	view {
		templateRootPaths.0 = EXT:myext/Resources/Private/Extensions/sic_address/Templates/
		partialRootPaths.0 = EXT:myext/Resources/Private/Extensions/sic_address/Partials/
		layoutRootPaths.0 = EXT:myext/Resources/Private/Extensions/sic_address/Layouts/
	}
}
```

Because of this line i think:
https://github.com/SicorDev/sic_address/blob/f9eee7f051773b1a39fd09dd9ec3bec547380a43/Classes/Controller/AddressController.php#L443

**Comment by SicorDev** [comment]
Hi, I just came back from vacation. Thanks for your feedback, I'll look into this and see if we can add support for multiple paths with an update.

**Comment by SicorDev** [comment]
Hi, we just uploaded a basic first solution to TER with version 1.1.2. We tested it with 7/8 LTS and Linux/Windows. Please let us know if it's good enough for you as well or if further adjustments are still required.

**Comment by nebrot** [comment]
We have tested it with outsourced "SPDirList.html" and this typoscript, works as expected. Thank you for this really fast enhancement and this great extension!

```
plugin.tx_sicaddress_sicaddress {
	view {
		templateRootPaths.100 = EXT:wkgsource/Resources/Private/Extensions/sic_address/Templates/
		partialRootPaths.100 = EXT:wkgsource/Resources/Private/Extensions/sic_address/Partials/
		layoutRootPaths.100 = EXT:wkgsource/Resources/Private/Extensions/sic_address/Layouts/
	}
}
```
