### ISSUE TITLE
Installation of sic_address without composer

### ISSUE THREAD

**Issue by Hogego** [SicorDev/sic_address#52]
Hi, trying to install this beautiful extension in a composer based installation I get an Error wich says:

Class 'SICOR\SicAddress\Utility\Service' not found

and in ext/sic_address/Configuration/TCA/Overrides/tx_sicaddress_domain_model_address.php line 5:
$extensionConfiguration = Service::getConfiguration();

Is there a way to get this to work?

Thanks a lot

**Comment by SicorDev** [comment]
I just released Version 4.0.0 officially for TYPO3 11.
Can you possibly try this version and see if it remedies your issues?
