### ISSUE TITLE
Backend: "No template was found"

### ISSUE THREAD

**Issue by lbehm** [SicorDev/sic_address#6]
Hi! Typo3 and extension development is kind of new to me, so this is maybe just a configuration problem.

I installed a fresh Typo3 8.7.15.
After installation of the extension (v1.1.2) via the extension manager and enabling the `developerMode`, I can't access the Adressverwaltung. I'm confronted with the following message (no styling/details):

    Sorry, the requested view was not found.

    The technical reason is: No template was found. View could not be resolved for action "list" in class "SICOR\SicAddress\Controller\ModuleController".

Enabling `addressExport` results in a prettier Typo3 exception on accessing the Adressexport, but this function isn't needed at the moment.

Hope you can help me out.

PS: continuing in german would be fine for me

**Comment by SicorDev** [comment]
Hallo, 
mein erster Gedanke wäre, dass evtl. das statische Template nicht eingebunden wurde? Ich meine das Backend Modul funktioniert nur in Ästen wo es auch hinzugefügt wurde. Gucke es mir dann gerne genauer an, aber das sollte vorab sichergestellt sein.

**Comment by lbehm** [comment]
> statische Template nicht eingebunden

Wie stelle ich das an?

**Comment by SicorDev** [comment]
Dafür gehen Sie normalerweise mit dem "List" Modul auf die Root Seite von dem Auftritt, und legen dort mit dem "+" Symbol aus dem Bereich "Systemdatensätze" ein "Template" an. Wenn Sie das Template editieren, fügen Sie dann auf dem Reiter "Enthält" den Eintrag für sic_address hinzu:

![grafik](https://user-images.githubusercontent.com/24271592/41297602-c7b36c60-6e5f-11e8-882e-e7fc5ce7c46c.png)

**Comment by SicorDev** [comment]
Hm... ich weiss gar nicht, was das Export Modul im quasi Leerlauf macht. Probieren Sie es bitte später nochmal, wenn Sie schon ein paar Test Adressen erstellt haben.

**Comment by SicorDev** [comment]
We just released version 1.1.3, which is giving a better error message when the backend module can't access the static tempate.
