### ISSUE TITLE
[Error] Using ${var} in strings is deprecated, use {$var} instead in OpenStreetMapViewHelper.php

### ISSUE THREAD

**Issue by bh-teufels** [SicorDev/sic_address#68]
PHP Runtime Deprecation Notice: Using ${var} in strings is deprecated, use {$var} instead in /app/web/typo3conf/ext/sic_address/Classes/ViewHelpers/OpenStreetMapViewHelper.php line 98

`L.tileLayer('$tileLayerUrl', $tileLayerSettings).addTo(sic_address_map_${id});`

occurs on FE-View List Modul

Environment:
Typo3: 11.5.27
PHP: 8.2.2
sic_address: master
tt_address: 7.1.0

Extension Settings:
basic.searchFields: company
basic.ttAddressMapping: true
modules.developerMode: true
templates.templateSet: sicor

FIX:
`L.tileLayer('$tileLayerUrl', $tileLayerSettings).addTo(sic_address_map_{$id});`

**Comment by SicorDev** [comment]
Thanks again, committed your suggestion. Please test!

**Comment by bh-teufels** [comment]
yes thank you error does not appear on latest version
