### ISSUE TITLE
[Error/Improvment] Created Domain Model Filename is lowercase

### ISSUE THREAD

**Issue by bh-teufels** [SicorDev/sic_address#72]
If i create a field with Type Mmtable it creates a myfield.php in Classes/Domain/Model 
Because it starts with lowercase i get Error that class 'Myfield' not exist.
If i change to Myfield.php (starts with uppercase) the error does not appear anymore, but with new "Generate model ..." the myfield.php (lowercase) is created again so 2 files with lower and uppercase exist

i think in terms of conventions, the generated "Domain/Model" file should always start with capital letter.

**Comment by SicorDev** [comment]
I commited changes for creation and deletion, please test.
