### ISSUE TITLE
add a sic_address tag for latest version 5.0.3

### ISSUE THREAD

**Issue by franzholz** [SicorDev/sic_address#81]
It is is not possible to install sic_address via composer.

```
composer req sicor/sic-address
Cannot use sicor/sic-address's latest version 4.1.0 as it requires php >=7.0 <=7.4 which is not satisfied by your platform.

In PackageDiscoveryTrait.php line 317:
                                                                                                                 
  Package sicor/sic-address has requirements incompatible with your PHP version, PHP extensions and Composer ve  
  rsion:                                                                                                         
    - sicor/sic-address 4.1.0 requires php >=7.0 <=7.4 which does not match your installed version 8.1.1 (Packa  
  ge overridden via config.platform, actual: 8.2.16).           

```

**Comment by SicorDev** [comment]
It tried. Did it work?

**Comment by franzholz** [comment]
Now it is working. The command fetches sic_address in version 5.0.3.

**Comment by franzholz** [comment]
However your tag is wrongly set to 5.3.0. It should have been **5.0.3** instead.

**Comment by SicorDev** [comment]
Tried again... there should be a Tag for 5.0.4 now...
Can't the composer just get the latest version anyway?

**Comment by franzholz** [comment]
Now there is a [5.0.4](https://github.com/SicorDev/sic_address/releases/tag/5.0.4) tag. This is perfect.
Composer can get the latest version, but the tag number must be identical to the TYPO3 extension version. Otherwise it gets only confusing.
