### ISSUE TITLE
Compatibility with TYPO3 9.5.x

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#9]
Hi,
do you plan an upgrade?

Kind regards

Hobokens

**Comment by Hobokens** [comment]
Thanks for good news. I tested the fork a little bit.  The installation is without any problem and I have a frontend view.

But I get the following when I save the plugin:

"Unknown column 'sys_category.sorting' in 'order clause'. Es ist ein SQL-Fehler aufgetreten. Dies kann auf eine Schema-Abweichung zwischen TCA und der Datenbank hindeuten. Versuchen Sie im Install Tool einen Datenbank-Vergleich durchzuführen."

One more question: Do you plan to add route enhancers?

Regards
Hobokens

**Comment by SicorDev** [comment]
Hi,

I have added a little hook in ext_tables.sql to fix this issue.

Install the beta fork again, please, and try it again. It should work now.

PS: The route enhancers will be added later.

**Comment by Hobokens** [comment]
Thanks a lot for the hook. The problem is solved. That's why I close this issue.
